databases:
  - name: dpg-chtthqndvk4olitu5vsg-a
    databaseName: knowledge_projectsdb
    user: knowledge_projectsdb_user

services:
  - type: web
    name: Knowledge_projects
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn knowledge_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: knowledge_projectsdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4