# Generated by Django 4.2 on 2023-04-19 16:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('nit', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='El NIT debe tener entre 9 y 10 dígitos', regex='^\\d{9,10}$')], verbose_name='NIT')),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe ser de formato '+57xxxxxxxxx'", regex='^\\+57\\d{8,10}$')], verbose_name='teléfono')),
                ('address', models.CharField(max_length=255, verbose_name='dirección')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('objective', models.TextField()),
                ('results', models.TextField()),
                ('reach', models.TextField()),
                ('state', models.CharField(choices=[('Propuesta', 'Propuesta'), ('En convocatoria', 'En convocatoria'), ('En factory', 'En factory')], default='Propuesta', max_length=20)),
                ('id_project', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kp_app.category')),
                ('company_nit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kp_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id_resource', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_role', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('phone', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe ser de formato '+57xxxxxxxxx'", regex='^\\+57\\d{8,10}$')])),
                ('email', models.EmailField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='correo electrónico')),
                ('birth_date', models.DateField()),
                ('full_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('cc', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='La cédula de ciudadanía debe contener entre 6 y 10 dígitos', regex='^\\d{6,10}$')])),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kp_app.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kp_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(through='kp_app.UserRole', to='kp_app.role'),
        ),
        migrations.AddField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(through='kp_app.UserRole', to='kp_app.user'),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company_nit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kp_app.company')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kp_app.project')),
                ('resource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kp_app.resource')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='user_cc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='kp_app.user'),
        ),
        migrations.CreateModel(
            name='Binnacle',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kp_app.project')),
                ('user_cc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kp_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id_announ', models.AutoField(primary_key=True, serialize=False)),
                ('init_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('projects_amount', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kp_app.category')),
                ('id_projects', models.ManyToManyField(to='kp_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='ResourcesBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kp_app.project')),
                ('resource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kp_app.resource')),
            ],
            options={
                'unique_together': {('project_id', 'resource_id')},
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.DecimalField(decimal_places=2, max_digits=10)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kp_app.project')),
                ('resource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kp_app.resource')),
            ],
            options={
                'unique_together': {('project_id', 'resource_id')},
            },
        ),
    ]
