# Generated by Django 4.2 on 2023-04-23 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe ser de formato '+57xxxxxxxxx'", regex='^\\+57\\d{10,10}$')], verbose_name='teléfono'),
        ),
    ]
