# Generated by Django 4.2 on 2023-04-14 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("kp_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="kp_app.category"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="user_cc",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company",
                to="kp_app.user",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="kp_app.category"
            ),
        ),
    ]
