# Generated by Django 4.2 on 2023-04-23 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kp_app', '0002_alter_company_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe ser de formato '+573xxxxxxxxx'", regex='^\\+573\\d{9,9}$')]),
        ),
    ]
