# Generated by Django 4.2 on 2023-04-16 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("kp_app", "0002_alter_announcement_category_alter_company_user_cc_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Binnacle",
            fields=[
                ("date", models.DateField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
                (
                    "project_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kp_app.project"
                    ),
                ),
                (
                    "user_cc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="kp_app.user"
                    ),
                ),
            ],
        ),
    ]
