# Generated by Django 4.2 on 2023-04-30 16:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="fecha_nacimiento",
            new_name="birth_date",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="nombre_completo",
            new_name="full_name",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="telefono",
            new_name="phone",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="foto",
            new_name="photo",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="cedula",
            new_name="user_cc",
        ),
    ]
