# Generated by Django 4.2 on 2023-05-02 03:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id_announ', models.AutoField(primary_key=True, serialize=False)),
                ('init_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('nit', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='El NIT debe tener entre 9 y 10 dígitos', regex='^\\d{9,10}$')], verbose_name='NIT')),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener de 8 a 10 dígitos', regex='\\d{8,10}$')], verbose_name='teléfono')),
                ('address', models.CharField(max_length=255, verbose_name='dirección')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(max_length=30)),
                ('objective', models.TextField()),
                ('results', models.TextField()),
                ('reach', models.TextField()),
                ('state', models.CharField(blank=True, choices=[('Propuesta', 'Propuesta'), ('En convocatoria', 'En convocatoria'), ('En factory', 'En factory')], default='Propuesta', max_length=20)),
                ('id_project', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_projects.category')),
                ('company_nit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_projects.company')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id_resource', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_projects.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company_nit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_projects.company')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_projects.project')),
                ('resource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_projects.resource')),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_projects.announcement')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_projects.category'),
        ),
        migrations.CreateModel(
            name='ResourcesBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_projects.project')),
                ('resource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_projects.resource')),
            ],
            options={
                'unique_together': {('project_id', 'resource_id')},
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.DecimalField(decimal_places=2, max_digits=10)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_projects.project')),
                ('resource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_projects.resource')),
            ],
            options={
                'unique_together': {('project_id', 'resource_id')},
            },
        ),
    ]
